services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin_go
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: api_database
    ports:
      - "5433:5432"

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      # PENTING: host di sini ganti jadi 'db' karena antar container 
      # berkomunikasi via nama service, bukan localhost
      DB_URL: "host=db user=admin_go password=password123 dbname=api_database port=5432 sslmode=disable"
    depends_on:
      - db